site_name: "Yichuan Wang's Homepage"
site_author: 'Yichuan Wang'
copyright: '&copy; 2022-2023 Yichuan Wang'
theme:
  name: material
  custom_dir: overrides
  palette:
    primary: white
    accent: orange
  icon:
    logo: material/account-school
  features:
    - navigation.indexes

nav:
  - Home: index.md
  - Blog:
      - blog/index.md
      - Research Vision:
          - Rethinking the Search Stack for the AI Era: blog/build-search-engine-for-AI.md
      - Production & Entrepreneurship Thoughts:
          - Rethinking RL as a Service and the Position of RL Infrastructure: blog/rethinking-rl-as-a-service.md
      - Tech Development Experience:
          - Mastering DiskANN - Practical Lessons from Large-Scale Vector Search: blog/How-to-build-diskANN-perfectly.md
          - Lessons Learned in Development - LEANN Project: blog/lessons_learned_in_dev_leann.md
      - Paper Reads:
          - Finally, a Retriever That Can Actually Reason (ReasonIR): blog/reasonir.md
          - Qwen3 Embedding: blog/qwen3embedding.md
          - My Thoughts on RAGCache: blog/ragcache.md
          - Exploring Orak - A Benchmark for LLM Agents in Games: blog/game_eval.md
      - Misc:
          - Reproducing OSS Agentic-RL Recipes — Status Summary: blog/oss-agentic-rl-reproduction.md
          - Opportunities in the Open-Source Agentic RL Landscape: blog/summer-plan.md

plugins:
  []
  
markdown_extensions:
  - meta
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons

extra:
  # social:
  #   - icon: fontawesome/solid/envelope 
  #     link: mailto:xcpan.mail@gmail.com
  #   - icon: academicons/google-scholar
  #     link: https://scholar.google.com/citations?user=9wh9VXIAAAAJ&hl=en
  #   - icon: academicons/semantic-scholar
  #     link: https://www.semanticscholar.org/author/Xichen-Pan/2158877024
  #   - icon: academicons/dblp
  #     link: https://dblp.org/pid/317/0180.html
  #   - icon: fontawesome/brands/github 
  #     link: https://github.com/xichenpan
  #   - icon: fontawesome/brands/linkedin 
  #     link: https://www.linkedin.com/in/xichenpan/
  #   - icon: fontawesome/brands/twitter
  #     link: https://twitter.com/xichen_pan
  #   - icon: fontawesome/brands/zhihu 
  #     link: https://www.zhihu.com/people/xichenpan
  analytics:
    provider: google
    property: G-KBQPT9Q9MJ
extra_css:
  - stylesheets/extra.css 
